# Generated by Django 3.0.5 on 2020-04-16 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, default='Remote', max_length=200)),
                ('availability', models.CharField(blank=True, default='Always', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratorSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_skill', models.CharField(max_length=200)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmInvisionLab.Collaborator')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmInvisionLab.Skill')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
