# Generated by Django 3.0.5 on 2020-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, default='Remote', max_length=200)),
                ('availability', models.CharField(blank=True, default='Always', max_length=200)),
                ('main_skills', models.CharField(blank=True, max_length=200)),
                ('secondary_skills', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
