# Generated by Django 3.0.5 on 2020-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0002_auto_20200421_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='secondary_skills',
            field=models.ManyToManyField(related_name='secondary_skills', to='crmInvisionLab.Skill'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='main_skills',
            field=models.ManyToManyField(related_name='main_skills', to='crmInvisionLab.Skill'),
        ),
    ]
