# Generated by Django 3.0.5 on 2020-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0003_auto_20200423_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='main_skills',
            field=models.ManyToManyField(blank=True, related_name='main_skills', to='crmInvisionLab.Skill'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='secondary_skills',
            field=models.ManyToManyField(blank=True, related_name='secondary_skills', to='crmInvisionLab.Skill'),
        ),
    ]
