# Generated by Django 3.0.5 on 2020-04-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0004_auto_20200423_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
