# Generated by Django 3.0.5 on 2020-04-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0005_auto_20200423_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='phone',
            field=models.PositiveIntegerField(max_length=200),
        ),
    ]
