# Generated by Django 3.0.5 on 2020-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0006_auto_20200424_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='phone',
            field=models.BigIntegerField(max_length=200),
        ),
    ]
