# Generated by Django 3.0.5 on 2020-04-24 09:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0008_auto_20200424_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, region='GB'),
        ),
    ]
