# Generated by Django 3.0.5 on 2020-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0011_job_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='preview',
            field=models.URLField(blank=True),
        ),
    ]
