# Generated by Django 3.0.5 on 2020-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0012_auto_20200513_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='ongoing_projects',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='past_collaborations',
        ),
        migrations.AddField(
            model_name='job',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators_involved', to='crmInvisionLab.Collaborator'),
        ),
    ]
