# Generated by Django 3.0.5 on 2020-05-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0013_auto_20200519_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to='crmInvisionLab.Collaborator'),
        ),
    ]
