# Generated by Django 3.0.5 on 2020-05-20 15:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0014_auto_20200519_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=200, region='GB')),
                ('position', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('projects_old', models.ManyToManyField(blank=True, related_name='old_projects', to='crmInvisionLab.Job')),
                ('projects_ongoing', models.ManyToManyField(blank=True, related_name='ongoing_projects', to='crmInvisionLab.Job')),
            ],
        ),
    ]
