# Generated by Django 3.0.5 on 2020-05-20 17:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0015_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='projects_old',
            new_name='old_projects',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='projects_ongoing',
            new_name='ongoing_projects',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=200, region='GB'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=200, region='GB'),
        ),
    ]
