# Generated by Django 3.0.5 on 2020-05-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0017_competitors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competitors',
            new_name='Competitor',
        ),
    ]
