# Generated by Django 3.0.5 on 2020-05-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0018_auto_20200527_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='contact_phone',
        ),
    ]
