# Generated by Django 3.0.5 on 2020-05-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmInvisionLab', '0019_auto_20200527_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='projects',
            new_name='showreel',
        ),
    ]
